[full ci]

diff --git a/.github/workflows/ci-test.yaml b/.github/workflows/ci-test.yaml
--- a/.github/workflows/ci-test.yaml
+++ b/.github/workflows/ci-test.yaml
@@ -17,7 +17,7 @@ env:
 
 jobs:
   media-similarity-tests:
-    needs: [text-similarity-tests]
+    # needs: [text-similarity-tests]
     runs-on: 
       group: check-runner
       labels: media
@@ -172,9 +172,9 @@ jobs:
        kill -9 $(pgrep ngrok)
     
   text-similarity-tests:
-    runs-on: 
-      group: check-runner
-      labels: text
+    runs-on: ubuntu-latest
+      # group: check-runner
+      # labels: text
     if: >
       github.ref == 'refs/heads/develop' ||
       github.ref == 'refs/heads/master' ||
@@ -324,17 +324,17 @@ jobs:
        docker compose exec web bash -c "[ -f test/file.json ] && python -m json.tool test/file.json || echo 'File does not exist'"
        size=$(du -k build/web/js/index.bundle.js | cut -f1) && size2=$(du -k build/web/js/vendor.bundle.js | cut -f1) && totalsize=$((size+size2)) && echo "Your bundle size is $totalsize kb"
 
-  cleanup-after-similarity-tests:
-    runs-on: self-hosted
-    needs: [media-similarity-tests, text-similarity-tests]
-    steps:
-      - name: Cleanup Docker Resources
-        if: always()
-        run: |
-          echo "Cleaning up Docker resources..."
-          docker stop $(docker ps -q) || true
-          docker rm $(docker ps -aq) || true
-          docker rmi $(docker images -q) || true
+  # cleanup-after-similarity-tests:
+  #   runs-on: self-hosted
+  #   needs: [media-similarity-tests, text-similarity-tests]
+  #   steps:
+  #     - name: Cleanup Docker Resources
+  #       if: always()
+  #       run: |
+  #         echo "Cleaning up Docker resources..."
+  #         docker stop $(docker ps -q) || true
+  #         docker rm $(docker ps -aq) || true
+  #         docker rmi $(docker images -q) || true
 
   integration-and-unit-tests:
     runs-on: ubuntu-latest
